language : java
sudo: required
jdk:
   - oraclejdk8

before_install:
   - curl http://www.jpm4j.org/install/script | sudo sh
   - sudo jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
   - mvn clean test jacoco:report coveralls:report
   - codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml --projectToken 196baa5e69c747a4a170488320cbc814

notifications:
  email:
    - flaesch.arnaud@esgi.fr